name:                 ad-delcont
version:              0.5.0.0
visibility:           public
id:                   ad-delcont-0.5.0.0-inplace
key:                  ad-delcont-0.5.0.0-inplace
license:              BSD-3-Clause
copyright:            (c) 2021 Marco Zocca
maintainer:           ocramz
author:               Marco Zocca
homepage:             https://github.com/ocramz/ad-delcont
synopsis:
    Reverse-mode automatic differentiation with delimited continuations

description:
    Reverse-mode automatic differentiation using delimited continuations (@shift@/@reset@).
    The package exposes a small and easily extensible user interface to automatic differentiation combinators. It's also lightweight as a dependency, since it only requires @base@ and @transformers@.

    To use the library, import "Numeric.AD.DelCont", which also contains all documentation.

    Blog post : http://ocramz.github.io/haskell/automatic-differentiation/2021/07/19/ad-delcont.html

    References :

    * F. Wang et al, Backpropagation with Continuation Callbacks : Foundations for Efficient and Expressive Differentiable Programming, NeurIPS 2018 - https://papers.nips.cc/paper/2018/file/34e157766f31db3d2099831d348a7933-Paper.pdf

    * F. Wang et al, Demystifying Differentiable Programming : Shift\/Reset the Penultimate Backpropagator, ICFP 2019 - https://www.cs.purdue.edu/homes/rompf/papers/wang-icfp19.pdf

category:             Math, Numeric, Machine Learning, Optimization, Optimisation
abi:                  inplace
exposed:              True
exposed-modules:      Numeric.AD.DelCont
hidden-modules:       Numeric.AD.DelCont.Internal
import-dirs:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/ad-delcont-0.5.0.0/build

library-dirs:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/ad-delcont-0.5.0.0/build

library-dirs-static:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/ad-delcont-0.5.0.0/build

dynamic-library-dirs:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/ad-delcont-0.5.0.0/build

data-dir:
    /Users/tonyday567/haskell/circuits-ad/../../other/ad-delcont/.

hs-libraries:         HSad-delcont-0.5.0.0-inplace
depends:              base-4.22.0.0-1f90 transformers-0.6.1.2-3c72
haddock-interfaces:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/ad-delcont-0.5.0.0/doc/html/ad-delcont/ad-delcont.haddock

haddock-html:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/ad-delcont-0.5.0.0/doc/html/ad-delcont
