name:                 circuits-ad
version:              0.1.0.0
visibility:           public
id:                   circuits-ad-0.1.0.0-inplace
key:                  circuits-ad-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           tonyday567@gmail.com
author:               Tony Day
synopsis:             Oracle tests: circuits reverse-mode AD against ad-delcont
abi:                  inplace
exposed:              True
exposed-modules:      Circuit.AD Circuit.AD.Oracle
import-dirs:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-ad-0.1.0.0/build

library-dirs:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-ad-0.1.0.0/build

library-dirs-static:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-ad-0.1.0.0/build

dynamic-library-dirs:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-ad-0.1.0.0/build

data-dir:             /Users/tonyday567/haskell/circuits-ad/.
hs-libraries:         HScircuits-ad-0.1.0.0-inplace
depends:
    ad-delcont-0.5.0.0-inplace base-4.22.0.0-1f90
    circuits-0.1.0.0-inplace transformers-0.6.1.2-3c72

haddock-interfaces:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-ad-0.1.0.0/doc/html/circuits-ad/circuits-ad.haddock

haddock-html:
    /Users/tonyday567/haskell/circuits-ad/dist-newstyle/build/aarch64-osx/ghc-9.14.1/circuits-ad-0.1.0.0/doc/html/circuits-ad
